using JCA.WorkSpace.Domain.Entities;
using JCA.WorkSpace.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace JCA.WorkSpace.Infrastructure.Data.Contexts;

public static class ModelBuilderExtensions
{
    public static void SeedData(this ModelBuilder modelBuilder)
    {
        var fixedDate = new DateTime(2026, 8, 30, 12, 0, 0, DateTimeKind.Utc);

        modelBuilder.Entity<Space>().HasData(
            new Space { Id = Guid.Parse("074891d0-865d-4bad-910a-f48e958f0f63"), Name = "2-01", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("57b94b5f-34f9-46a8-bc11-63b0d0e0ec38"), Name = "2-02", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("38d0959b-562b-43d1-828c-23aeec84ebaa"), Name = "2-03", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("cafcc90a-a877-44bd-b042-4b3181a9ffd5"), Name = "2-04", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("0f66b089-4284-4021-afff-7b22c98ff2c4"), Name = "2-05", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("682027d2-2714-4c8f-85ad-d8646e3e4e9d"), Name = "2-06", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("034deb20-a8b7-47fb-84cb-2307097d9ff9"), Name = "2-07", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("5576496d-e0ae-45bf-9a7e-4afaec6d2350"), Name = "2-08", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("8ac132c5-0d7d-411c-b45c-f46da932c038"), Name = "2-09", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("63c55eb2-f95b-4456-b043-da4a3d54f84a"), Name = "2-10", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("2bb84bec-6dcf-4b76-b28b-54ed738eba85"), Name = "2-11", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("3892b8f1-8a06-47ad-8474-a7f19d7cdd07"), Name = "2-12", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("832d750e-bc75-4a74-bf9a-70228c025e62"), Name = "2-13", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("0620795e-c3ec-40f7-926a-651b6885948c"), Name = "2-14", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("41269cfb-a272-4037-a747-01a43d2b1502"), Name = "2-15", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("1012d99a-53a0-4770-820c-139fafad06d2"), Name = "2-16", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("e3f7be87-a65a-4d2d-9bbc-56e1eb881510"), Name = "2-17", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("8b3f9fb4-ff21-4bb1-ad3f-eb6febd3f98b"), Name = "2-18", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("92c7622e-7c05-4ba9-bceb-80d6719f9462"), Name = "2-19", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("b24ee01e-97dc-4b53-8916-df3e6ac93697"), Name = "2-20", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("58a1667c-149f-4662-ab61-9f5111d9a43e"), Name = "2-21", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("73a3650f-723a-44d0-987d-7c2d058e246e"), Name = "2-22", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("2af44327-4f36-4891-95d4-a645794bd16e"), Name = "2-23", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("dd33a6a2-e638-4f83-be28-16259abcc06c"), Name = "2-24", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("4c497dbf-0b67-4398-8de0-6949c56b9616"), Name = "2-25", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("1914bfa2-a320-46d2-8e50-911c4b56fe3e"), Name = "2-26", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("b3824ddf-8af7-49a4-a8a1-1a72e840a5f9"), Name = "2-27", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("9fd4a58b-2f74-4013-b59b-d296e9743484"), Name = "2-28", Type = SpaceType.Desk, Floor = 2, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },

            new Space { Id = Guid.Parse("5b6e191e-6395-4ed1-a0a8-b7d5dc00421a"), Name = "Florianopolis", Type = SpaceType.Room, Floor = 2, Capacity = 3, IsBlocked = false, MaintenanceReason = null, Resources = "[\"Televisao\"]", RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("dde63f09-d4fe-4817-a9b8-a9ca8c304500"), Name = "Curitiba", Type = SpaceType.Room, Floor = 2, Capacity = 3, IsBlocked = false, MaintenanceReason = null, Resources = "[\"Televisão\"]", RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("a090562b-4727-4503-b4ac-118867d3fbd5"), Name = "Belo Horizonte", Type = SpaceType.Room, Floor = 2, Capacity = 6, IsBlocked = false, MaintenanceReason = null, Resources = "[\"Televisao\", \"Quadro Branco\"]", RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("0b51cbe6-6556-4f95-a10c-85d4c4d31715"), Name = "Niteroi", Type = SpaceType.Room, Floor = 2, Capacity = 6, IsBlocked = false, MaintenanceReason = null, Resources = "[\"Televisao\", \"Quadro Branco\"]", RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("1da6f2ea-94fb-4be1-8994-3124c96b1d41"), Name = "Rio de Janeiro", Type = SpaceType.Room, Floor = 2, Capacity = 6, IsBlocked = false, MaintenanceReason = null, Resources = "[\"Televisao\", \"Quadro Branco\"]", RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("7dcc8363-cb31-46c5-98e6-1398880f5be6"), Name = "Sao Paulo", Type = SpaceType.Room, Floor = 2, Capacity = 6, IsBlocked = false, MaintenanceReason = null, Resources = "[\"Televisao\", \"Quadro Branco\"]", RequiresApproval = false, CreatedAt = fixedDate },

            new Space { Id = Guid.Parse("432ad042-c232-4978-bf4f-2702ffa5c50e"), Name = "13-01", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("4b7d016b-10e7-4432-8a58-09d53638a5d5"), Name = "13-02", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("063c9b01-3f5d-47cc-8eb3-c11420ee51ef"), Name = "13-03", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("0d47d2d2-28a6-41bd-bfba-f2fad4b47adb"), Name = "13-04", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("56424624-b986-4cb3-b753-5334bbe3a37a"), Name = "13-05", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("c65fff0c-7bd4-45ef-85ca-35cdc555e1e0"), Name = "13-06", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("d270041a-e90b-420a-afb1-290fe151532c"), Name = "13-07", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("fef71b26-4c06-47e5-9662-c798cc272fe6"), Name = "13-08", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("8f4a29bf-6406-47a8-bace-a6630c90f708"), Name = "13-09", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("6dff7e65-25f1-429f-975b-97a88f9767fe"), Name = "13-10", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("8c27cc2b-abb0-4249-b2ed-5bf429663e1e"), Name = "13-11", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("f7ed0663-e165-4150-9096-ff945dec5a72"), Name = "13-12", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("42ea4728-e769-43f8-b501-5c2ed7fe67a9"), Name = "13-13", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("a28072a5-cd15-40fb-a97d-fdb4dfd51bc1"), Name = "13-14", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("79ed3bae-7507-4999-8023-45ab19b86fac"), Name = "13-15", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("261590d7-0941-4184-89bb-8009ebf94bab"), Name = "13-16", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("628f5df5-6922-4c8d-bbed-df761060978a"), Name = "13-17", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("9ee24207-2587-439d-a150-39181b024f66"), Name = "13-18", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("70b79960-5abb-42b4-9b9d-b86acbbed145"), Name = "13-19", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("1b6dc520-fb40-4d3a-9854-c7537413e375"), Name = "13-20", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("7365a113-a0c1-48aa-bea1-ef9499b3050c"), Name = "13-21", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("cdb4d95d-5eb9-4653-9bf6-7c66e0133592"), Name = "13-22", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("cfeeae31-5cf0-4376-a030-cdb1cc48aee0"), Name = "13-23", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("01591087-9e8c-4670-8cf3-c8835bfa8374"), Name = "13-24", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("96d31551-5323-4885-a520-37ce9feb1347"), Name = "13-25", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("d3e72e61-d3f8-4d3f-b071-eb9b1622abfa"), Name = "13-26", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("34f0b4f5-3cab-4424-b676-fd4c4d2711e3"), Name = "13-27", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("65ce02e9-663d-450e-b61d-3b9aeebae045"), Name = "13-28", Type = SpaceType.Desk, Floor = 13, Capacity = 1, IsBlocked = false, MaintenanceReason = null, Resources = null, RequiresApproval = false, CreatedAt = fixedDate },

            new Space { Id = Guid.Parse("bc6df773-9ca7-433a-84fc-139a9e8c4211"), Name = "Clube Giro", Type = SpaceType.Room, Floor = 13, Capacity = 10, IsBlocked = false, MaintenanceReason = null, Resources = "[\"Televisao\", \"Quadro Branco\"]", RequiresApproval = true, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("a5f1bb90-dd63-4069-8fa5-9c20f9f2e704"), Name = "Outlet de passagens", Type = SpaceType.Room, Floor = 13, Capacity = 14, IsBlocked = false, MaintenanceReason = null, Resources = "[\"Projetor\", \"Quadro Branco\"]", RequiresApproval = true, CreatedAt = fixedDate },
            new Space { Id = Guid.Parse("ff0b2247-f0ec-4907-ae76-decfea7593f1"), Name = "WeMobi", Type = SpaceType.Room, Floor = 13, Capacity = 4, IsBlocked = false, MaintenanceReason = null, Resources = "[\"Televisao\"]", RequiresApproval = false, CreatedAt = fixedDate }
        );
    }
}