// <auto-generated />
using System;
using JCA.WorkSpace.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JCA.WorkSpace.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WorkSpaceContext))]
    [Migration("20260914031320_SeedDeskandRoom")]
    partial class SeedDeskandRoom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "reservation_status", new[] { "pending", "checked_in", "canceled", "no_show", "completed", "awaiting_approval" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "space_type", new[] { "desk", "room" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_profile", new[] { "employee", "manager", "facilities", "admin" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JCA.WorkSpace.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("idx_auditlogs_action");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("idx_auditlogs_entityid");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("JCA.WorkSpace.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("idx_reservations_batchid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_reservations_userid");

                    b.HasIndex("SpaceId", "StartTime")
                        .HasDatabaseName("idx_reservations_space_date");

                    b.HasIndex("Status", "StartTime")
                        .HasDatabaseName("idx_reservations_status_date");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("JCA.WorkSpace.Domain.Entities.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MaintenanceReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("MaintenanceUntil")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("Resources")
                        .HasColumnType("jsonb");

                    b.Property<string>("Sector")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Floor")
                        .HasDatabaseName("idx_spaces_floor");

                    b.ToTable("Spaces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("074891d0-865d-4bad-910a-f48e958f0f63"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-01",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("57b94b5f-34f9-46a8-bc11-63b0d0e0ec38"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-02",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("38d0959b-562b-43d1-828c-23aeec84ebaa"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-03",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("cafcc90a-a877-44bd-b042-4b3181a9ffd5"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-04",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("0f66b089-4284-4021-afff-7b22c98ff2c4"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-05",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("682027d2-2714-4c8f-85ad-d8646e3e4e9d"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-06",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("034deb20-a8b7-47fb-84cb-2307097d9ff9"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-07",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("5576496d-e0ae-45bf-9a7e-4afaec6d2350"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-08",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("8ac132c5-0d7d-411c-b45c-f46da932c038"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-09",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("63c55eb2-f95b-4456-b043-da4a3d54f84a"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-10",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("2bb84bec-6dcf-4b76-b28b-54ed738eba85"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-11",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("3892b8f1-8a06-47ad-8474-a7f19d7cdd07"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-12",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("832d750e-bc75-4a74-bf9a-70228c025e62"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-13",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("0620795e-c3ec-40f7-926a-651b6885948c"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-14",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("41269cfb-a272-4037-a747-01a43d2b1502"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-15",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("1012d99a-53a0-4770-820c-139fafad06d2"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-16",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("e3f7be87-a65a-4d2d-9bbc-56e1eb881510"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-17",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("8b3f9fb4-ff21-4bb1-ad3f-eb6febd3f98b"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-18",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("92c7622e-7c05-4ba9-bceb-80d6719f9462"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-19",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("b24ee01e-97dc-4b53-8916-df3e6ac93697"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-20",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("58a1667c-149f-4662-ab61-9f5111d9a43e"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-21",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("73a3650f-723a-44d0-987d-7c2d058e246e"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-22",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("2af44327-4f36-4891-95d4-a645794bd16e"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-23",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("dd33a6a2-e638-4f83-be28-16259abcc06c"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-24",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("4c497dbf-0b67-4398-8de0-6949c56b9616"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-25",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("1914bfa2-a320-46d2-8e50-911c4b56fe3e"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-26",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("b3824ddf-8af7-49a4-a8a1-1a72e840a5f9"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-27",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("9fd4a58b-2f74-4013-b59b-d296e9743484"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "2-28",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("5b6e191e-6395-4ed1-a0a8-b7d5dc00421a"),
                            Capacity = 3,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "Florianopolis",
                            RequiresApproval = false,
                            Resources = "[\"Televisao\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("dde63f09-d4fe-4817-a9b8-a9ca8c304500"),
                            Capacity = 3,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "Curitiba",
                            RequiresApproval = false,
                            Resources = "[\"Televisão\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("a090562b-4727-4503-b4ac-118867d3fbd5"),
                            Capacity = 6,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "Belo Horizonte",
                            RequiresApproval = false,
                            Resources = "[\"Televisao\", \"Quadro Branco\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("0b51cbe6-6556-4f95-a10c-85d4c4d31715"),
                            Capacity = 6,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "Niteroi",
                            RequiresApproval = false,
                            Resources = "[\"Televisao\", \"Quadro Branco\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("1da6f2ea-94fb-4be1-8994-3124c96b1d41"),
                            Capacity = 6,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "Rio de Janeiro",
                            RequiresApproval = false,
                            Resources = "[\"Televisao\", \"Quadro Branco\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("7dcc8363-cb31-46c5-98e6-1398880f5be6"),
                            Capacity = 6,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 2,
                            IsBlocked = false,
                            Name = "Sao Paulo",
                            RequiresApproval = false,
                            Resources = "[\"Televisao\", \"Quadro Branco\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("432ad042-c232-4978-bf4f-2702ffa5c50e"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-01",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("4b7d016b-10e7-4432-8a58-09d53638a5d5"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-02",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("063c9b01-3f5d-47cc-8eb3-c11420ee51ef"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-03",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("0d47d2d2-28a6-41bd-bfba-f2fad4b47adb"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-04",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("56424624-b986-4cb3-b753-5334bbe3a37a"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-05",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("c65fff0c-7bd4-45ef-85ca-35cdc555e1e0"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-06",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("d270041a-e90b-420a-afb1-290fe151532c"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-07",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("fef71b26-4c06-47e5-9662-c798cc272fe6"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-08",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("8f4a29bf-6406-47a8-bace-a6630c90f708"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-09",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("6dff7e65-25f1-429f-975b-97a88f9767fe"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-10",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("8c27cc2b-abb0-4249-b2ed-5bf429663e1e"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-11",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("f7ed0663-e165-4150-9096-ff945dec5a72"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-12",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("42ea4728-e769-43f8-b501-5c2ed7fe67a9"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-13",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("a28072a5-cd15-40fb-a97d-fdb4dfd51bc1"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-14",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("79ed3bae-7507-4999-8023-45ab19b86fac"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-15",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("261590d7-0941-4184-89bb-8009ebf94bab"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-16",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("628f5df5-6922-4c8d-bbed-df761060978a"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-17",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("9ee24207-2587-439d-a150-39181b024f66"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-18",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("70b79960-5abb-42b4-9b9d-b86acbbed145"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-19",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("1b6dc520-fb40-4d3a-9854-c7537413e375"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-20",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("7365a113-a0c1-48aa-bea1-ef9499b3050c"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-21",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("cdb4d95d-5eb9-4653-9bf6-7c66e0133592"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-22",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("cfeeae31-5cf0-4376-a030-cdb1cc48aee0"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-23",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("01591087-9e8c-4670-8cf3-c8835bfa8374"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-24",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("96d31551-5323-4885-a520-37ce9feb1347"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-25",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("d3e72e61-d3f8-4d3f-b071-eb9b1622abfa"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-26",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("34f0b4f5-3cab-4424-b676-fd4c4d2711e3"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-27",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("65ce02e9-663d-450e-b61d-3b9aeebae045"),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "13-28",
                            RequiresApproval = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("bc6df773-9ca7-433a-84fc-139a9e8c4211"),
                            Capacity = 10,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "Clube Giro",
                            RequiresApproval = true,
                            Resources = "[\"Televisao\", \"Quadro Branco\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("a5f1bb90-dd63-4069-8fa5-9c20f9f2e704"),
                            Capacity = 14,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "Outlet de passagens",
                            RequiresApproval = true,
                            Resources = "[\"Projetor\", \"Quadro Branco\"]",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("ff0b2247-f0ec-4907-ae76-decfea7593f1"),
                            Capacity = 4,
                            CreatedAt = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Floor = 13,
                            IsBlocked = false,
                            Name = "WeMobi",
                            RequiresApproval = false,
                            Resources = "[\"Televisao\"]",
                            Type = 2
                        });
                });

            modelBuilder.Entity("JCA.WorkSpace.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Profile")
                        .HasColumnType("integer");

                    b.Property<string>("Sector")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("JCA.WorkSpace.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("JCA.WorkSpace.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("JCA.WorkSpace.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("JCA.WorkSpace.Domain.Entities.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JCA.WorkSpace.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Space");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
